###
POST http://localhost:3000/customers
Content-Type: application/json

{
  "name": "lucas 4",
  "email": "test@test"
}

###
GET http://localhost:3000/customers/

###

PUT http://localhost:3000/customers/65e8de939ed0164626886666
Content-Type: application/json

{
  "name": "Teste hora 2"
}

###
DELETE http://localhost:3000/customers?id=65e8f1ac27f68c5abcd10301
